defaults:
  user: revp
  port: 22
  key_file: /app/ssh-keys/docker_monitor_key
  enabled: true
hosts:
  dev:
    hostname: 192.168.86.78
    user: revp
    port: 22
    key_file: /app/ssh-keys/docker_monitor_key
    description: Local Docker host via SSH
    enabled: true
  media-arr:
    hostname: 192.168.86.229
    user: revp
    port: 22
    key_file: /app/ssh-keys/docker_monitor_key
    description: ARR containers
    enabled: true
  fabric:
    hostname: 192.168.86.145
    user: revp
    port: 22
    key_file: /app/ssh-keys/docker_monitor_key
    description: ''
    enabled: true
ssh_config:
  timeout: 30
  retries: 3
  keepalive: 60
  options:
    StrictHostKeyChecking: 'no'
    UserKnownHostsFile: /dev/null
    ServerAliveInterval: '60'
    ServerAliveCountMax: '3'
    CanonicalizeHostname: 'no'
discovery:
  labels:
    enable_label: dcrp.enable
    host_label: dcrp.host
    port_label: dcrp.port
    ssl_label: dcrp.ssl
    websocket_label: dcrp.websocket
    path_label: dcrp.path
    auth_label: dcrp.auth
    middleware_label: dcrp.middleware
  networks:
  - dcrp-network
  port_scan:
    enabled: false
    common_ports:
    - 80
    - 443
    - 3000
    - 8000
    - 8080
    - 9000
monitoring:
  events:
  - start
  - stop
  - restart
  - pause
  - unpause
  - die
  health_check_interval: 60
  cleanup_interval: 300
  retry:
    max_attempts: 3
    backoff_factor: 2
    max_delay: 300
