static_routes:
  colossus:
    host: colossus.isnadboy.com
    upstream_protocol: https
    upstream_host: host-colossus.isnadboy.com
    upstream_port: 8006
    description: Static route test
  ns_isnadboy_com:
    host: ns.isnadboy.com
    upstream_protocol: http
    upstream_host: host-ns.isnadboy.com
    upstream_port: 5380
    description: Static route added via API
